#!/usr/bin/python

import StringIO
import subprocess
import requests
from sys import argv
from os.path import expanduser


CONFIG = expanduser("~") + "/.config/lazy-snake/client"
URL = "http://lazysnake-frostyx.rhcloud.com/"
try:
	f = open(CONFIG, "r")
	line = f.readline()
	if line.startswith("URL"):
		URL = line[3:].strip()[1:].strip()
	f.close()
except IOError:
	pass


def render_help():
	print "Lazy Snake"
	print "  A terminal client for web based python profiler"
	print ""
	print "  Usage:"
	print "    lazy-snake path/to/some/script.py"


def main(script):
	process = subprocess.Popen(["python", "-m", "cProfile", script], stdout=subprocess.PIPE)
	out = process.communicate()[0]
	f = StringIO.StringIO(out)

	try:
		r = requests.post(URL, files={"result": f}, data={"post_file": "post"})
		if r.url == URL:
			print "Some error occurred"
			return
		print "Your result can be analyzed here: " + r.url

	except requests.exceptions.ConnectionError:
		print "Could not connect to server"


if __name__ == "__main__":
	main(argv[1]) if(len(argv) > 1) else render_help()
